name = "LinearProgramDebugging"
uuid = "987fedc8-4679-486d-b3d4-8ea116e1f9e2"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
HiGHS = "1"
JuMP = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
